config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get '/dashboard', to: 'pages#dashboard', as: :dashboard
  resources :profiles do
    resources :hangouts, only: [:new, :create]
  end

  get '/components', to: 'pages#components', as: :components

  resources :hangouts, only: [:show, :destroy, :edit, :update] do
    resources :reviews, only: [:new, :create, :destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/hangout.rb
class Hangout < ApplicationRecord
  attr_accessor :seed

  belongs_to :user
  belongs_to :profile
  has_one :review, dependent: :destroy
  # validates :date, comparison: { greater_than: Date.today }
  validates :time, presence: true


  validates :date, presence: true
  validate :date_future?, on: :create
  before_create :set_default_status

  def seen!
    update(seen: true)
  end

  private

  def set_default_status
    self.status = 'pending'
  end

  def date_future?
    return if seed
    return if !date.present?
    errors.add(:date, "can't be in the past") if date < Date.today
  end
end

app/models/profile.rb
class Profile < ApplicationRecord
  GENRES = %w[male female other]


  INTERESTS = ["Business", "Film", "Family", "Fitness", "Food", "Art", "Music", "Shopping", "Sports", "Tech"]


  has_one_attached :photo
  belongs_to :user
  validates :name, :age, :gender, :interest, presence: true
  validates :age, numericality: { only_integer: true, greater_than_or_equal_to: 18 }
  validates :gender, inclusion: {
    in: GENRES,
    message: "%{value} is not a valid gender. (Male, female, other.)"
  }
  has_many :hangouts, dependent: :destroy
  has_many :reviews, through: :hangouts
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
end

# add bio + interests

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :hangout
  belongs_to :user
  # belongs_to :profile, through: :hangouts
  validates :comment, length: { minimum: 10,
    too_short: "%{count} characters is the minimum allowed" }
  validates :rating, numericality: {only_integer: true, greater_than_or_equal_to: 1, less_than_or_equal_to: 5}

  after_create :calc_avg_profile

  def calc_avg_profile
    profile = self.hangout.profile
    sum = 0
    count = 0
    profile.hangouts.each do |hangout|
      unless hangout.review.nil?
        sum += hangout.review.rating
        count += 1
      end
    end
    profile.average_rating = (sum.to_f / count) unless count.zero?
    profile.save
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_one :profile
  has_many :reviews
  has_many :hangouts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  include Pundit

  before_action :set_notification

  # Pundit: white-list approach.
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  # Uncomment when you *really understand* Pundit!
  # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  # def user_not_authorized
  #   flash[:alert] = "You are not authorized to perform this action."
  #   redirect_to(root_path)
  # end

  private

  def set_notification
    return if !user_signed_in? || current_user.profile.nil?
    @notification = Hangout.where(profile: current_user.profile, seen: false).size
  end

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end


end

app/controllers/hangouts_controller.rb
class HangoutsController < ApplicationController
  before_action :set_hangout, only: %i[show edit update destroy]
  before_action :find_profile, only: %i[create new]

  def index
    @hangouts = policy_scope(Hangout)
  end

  def show
    if @hangout.review.nil?
      @review = Review.new
      @review.hangout = @hangout
      @review.user = @hangout.user
    end
  end

  def new
    @hangout = Hangout.new
    authorize @hangout
  end

  def create
    @hangout = Hangout.new(hangout_params)
    # link the bookmark to the restaurant
    @hangout.profile = @profile
    @hangout.user = current_user
    authorize @hangout
    if @hangout.save
      redirect_to hangout_path(@hangout)
      flash[:notice] = 'Your booking has benn saved!'
    else
      render 'profiles/show'
    end
  end

  def edit
    @hangout = Hangout.find(params[:id])
  end

  def update
    @hangout.update(hangout_params)
    authorize @hangout
    redirect_to dashboard_path
  end

  def destroy
    @hangout.destroy
    authorize @hangout
    redirect_to dashboard_path
  end

  private

  def set_hangout
    @id = params[:id]
    @hangout = Hangout.find(@id)
    authorize @hangout
  end

  def find_profile
    @profile = Profile.find(params[:profile_id])
  end

  def hangout_params
    params.require(:hangout).permit(:date, :time, :status)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home
  def home
    redirect_to(profiles_path) if user_signed_in?
  end

  def dashboard
    @hangouts = Hangout.where(user: current_user)
    @requests = Hangout.where(profile: current_user.profile)
  end

  def components
    @profiles = Profile.all.sample(6)
    @hangouts = Hangout.all.sample(5)
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile, only: %i[show destroy edit update]
  def index
    @profiles = policy_scope(Profile).order(created_at: :desc)

    if params[:address] == "All"
      @profiles = policy_scope(Profile)
    elsif params[:address].present?
      @profiles = @profiles.near(params[:address])
    end

    @profiles = @profiles.where(gender: params[:gender]) if params[:gender].present?

    if params[:min_age].present? && params[:max_age].present?
      @profiles = @profiles.where("profiles.age BETWEEN #{params[:min_age]} and #{params[:max_age]}")
    elsif params[:min_age].present?
      @profiles = @profiles.where("profiles.age > #{params[:min_age]}")
    elsif params[:max_age].present?
      @profiles = @profiles.where("profiles.age < #{params[:max_age]}")
    end

    if params[:interests].present?
      profiles_filter = []
      @profiles.each do |profile|
        profile_interest = profile.interest.split(" ")
        params[:interests].each do |interest|
          profiles_filter << profile if profile_interest.include?(interest)
        end
      end
      @profiles = profiles_filter

    end

    @markers = @profiles.map do |profile|
      {
        lat: profile.latitude,
        lng: profile.longitude

      }
    end
  end

  def show
    @profile = Profile.find(params[:id])
    @hangout = Hangout.new
    @hangout.profile = @profile
  end

  def new
    @profile = Profile.new
    authorize @profile
  end

  def create
    @profile = Profile.new(profile_params)
    authorize @profile
    @profile.user = current_user
    if @profile.save
      redirect_to profile_path(@profile)
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    @profile.update(profile_params)
    authorize @profile
    if @profile.save
      redirect_to profile_path(@profile)
    else
      render 'edit'
    end
  end

  def destroy
    @profile.destroy
    authorize @profile
    redirect_to profiles_path
  end

  private

  def profile_params
    params.require(:profile).permit(:name, :age, :gender, :address, :photo, interest: [])
  end

  def set_profile
    @profile = Profile.find(params[:id])
    authorize @profile
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :find_review, only: %(destroy create)

  def create
    @review = Review.new(review_params)
    @review.hangout_id = params[:hangout_id]
    @review.user = current_user
    authorize @review
    if @review.save
      redirect_to hangout_path(@review.hangout)
    else
      render "hangouts/show"
    end
  end

  def destroy
    @hangout.delete
  end

  def review_params
    params.require(:review).permit(:comment, :rating)
  end

  def find_review
    @hangout = Hangout.find(params[:hangout_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/hangouts/edit.html.erb
<!-- Flex box containing Title and Avatar -->
<div class="responsive-avatar-title">
  <div class="ml-5 pl-4">
    <h1 >Edit hangout:</h1>
    <h1 class="my-4"><span class="blue-font"><%= @hangout.profile.name %></span></h1>
  </div>
  <div>
    <div class="d-flex align-items-center justify-content-center">
      <% if @hangout.profile.photo.attached? %>
      <%= cl_image_tag @hangout.profile.photo.key, class: "avatar-hangout" %>
      <% else %>
      <%= cl_image_tag "avatar_ivxvwp", class: "avatar-hangout" %>
      <% end %>
    </div>
  </div>
</div>

<!-- Edit Form -->
<div class="pl-5 ml-4">
  <%= form_for [@profile, @hangout] do |f| %>
    <p class="mb-0">
      <%= f.label :date, 'date:', class: 'review-form-label' %>
    </p>
    <p class="mb-0">
      <%= f.date_field :date, data:{ provide:'datepicker' } %>
    </p>
    <p class="mb-0">
      <%= f.label :time, 'time:', class: 'review-form-label' %>
    </p>
    <p class="mb-4">
      <%= f.time_select :time, class: 'review-form-input' %>
    </p>
    <div class="d-flex align-items-center">
      <p class="mb-0">
      <%= f.submit "Edit", class: 'hangout-edit-button' %>
    </p>
    <p class="mb-0 ">
      <%= link_to 'Back', dashboard_path, class: "hangout-button" %></p>
    </div>
  <% end %>
</div>

app/views/hangouts/show.html.erb
<!-- Flex box containing Title and Avatar -->
<div class="responsive-avatar-title">
  <div class="ml-5 pl-4">
    <% if current_user == @hangout.user %>
    <h1 >Hangout with</h1>
    <h1 class="my-4"><span class="blue-font"><%= @hangout.profile.name %></span></h1>
    <% else %>
    <h1>Request from</h1>
    <% name_array = @hangout.user.email.split('@')[0] %>
    <h1 class="my-4"><span class="blue-font"><%= name_array %></span></h1>
    <% end %>
  </div>
  <div>
    <div class="d-flex align-items-center justify-content-center">
      <% if @hangout.profile.photo.attached? %>
      <%= cl_image_tag @hangout.profile.photo.key, class: "avatar-hangout" %>
      <% else %>
      <%= cl_image_tag "avatar_ivxvwp", class: "avatar-hangout" %>
      <% end %>
    </div>
  </div>
</div>

<!-- Status and date/time -->
<div class="notification-content">
  <% if @hangout.status == "pending" %>
    <p class="ml-5 pl-4">Status: <span class="status-color-red"><%= @hangout.status %><span></p>
  <% elsif @hangout.status == "accepted" %>
    <p class="status-color-green ml-5 pl-4"><%= @hangout.status %></p>
  <% else %>
    <p class="status-color-blue ml-5 pl-4"><%= @hangout.status %></p>
  <% end %>
  <p class="ml-5 pl-4 mb-4.5">When: <%= @hangout.date.strftime("%b %d, %Y") %> <%= @hangout.time.strftime("%I:%M %p") %></p>
</div>

<!-- Reviews -->

<div class="ml-5 pl-4 mt-4">
  <div>
    <!-- Review displayed -->
    <% if @hangout.review && @hangout.review.persisted? %>
    <% name_array = @hangout.review.user.email.split('@')[0] %>
    <p><%= name_array %>'s review:</p>
    <div class="d-flex">
      <p class="mr-5">
        <% case @hangout.review.rating %>
        <% when 1 %>
        <span class="fa checked"></span>
        <span class="fa unchecked"></span>
        <span class="fa fa-star unchecked"></span>
        <span class="fa fa-star unchecked"></span>
        <span class="fa fa-star unchecked"></span>
        <% when 2 %>
        <span class="fa fa-star checked"></span>
        <span class="fa fa-star checked"></span>
        <span class="fa fa-star unchecked"></span>
        <span class="fa fa-star unchecked"></span>
        <span class="fa fa-star unchecked"></span>
        <% when 3 %>
        <span class="fa fa-star checked"></span>
        <span class="fa fa-star checked"></span>
        <span class="fa fa-star checked"></span>
        <span class="fa fa-star unchecked"></span>
        <span class="fa fa-star unchecked"></span>
        <% when 4 %>
        <span class="fa fa-star checked"></span>
        <span class="fa fa-star checked"></span>
        <span class="fa fa-star checked"></span>
        <span class="fa fa-star checked"></span>
        <span class="fa fa-star unchecked"></span>
        <% when 5 %>
        <span class="fa fa-star checked"></span>
        <span class="fa fa-star checked"></span>
        <span class="fa fa-star checked"></span>
        <span class="fa fa-star checked"></span>
        <span class="fa fa-star checked"></span>
        <% end %>
      </p>
      <p class="mr-3"><%= @hangout.review.comment %></p>
    </div>



    <% elsif policy(@review).create? %>
      <div>
        <%= form_for [@hangout, @review] do |f| %>
          <p class="mb-0">
            <%= f.label :comment, 'comment:', class: 'review-form-label' %>
          </p>
          <p class="mb-0">
            <%= f.text_area :comment, class: 'review-form-comment-input' %>
          </p>
          <p class="mb-0">
            <%= f.label :rating, 'rating:', class: 'review-form-label' %>
          </p>
          <p class="mb-4">
            <%= f.select :rating, [5, 4, 3, 2, 1], class: 'review-form-input' %>
          </p>
          <p class="mb-0">
            <%= f.submit "Save", class: 'hangout-save-button' %>
          </p>
        <% end %>
      </div>
    <% end %>
  </div>

</div>


<!-- Buttons -->
<div class="hangout-button-div">
  <%# Update and complete button %>
  <div class="top-buttons">
    <% if policy(@hangout).update? && current_user == @hangout.user && @hangout.status != "pending" && @hangout.status != "completed"%>
    <%= link_to 'Edit', edit_hangout_path(@hangout), class: "hangout-button" %>
    <%= link_to 'Complete', hangout_path(@hangout, hangout: {status: "completed"}), method: :patch, class: "hangout-button", data: { confirm: "Are you sure?" }%>
    <% end %>
  </div>
  <div>
    <%# Delete button %>
    <% if policy(@hangout).destroy? %>
      <%= link_to "Delete", hangout_path(@hangout), class: "hangout-button", method: :delete, data: { confirm: "Are you sure?" } %>
    <% end %>
      <%# Accept and Reject button %>
    <% if current_user.profile == @hangout.profile && @hangout.status == "pending" %>
        <%= link_to 'Accept', hangout_path(@hangout, hangout: {status: "accepted"}), method: :patch, class: "hangout-button" %>
        <%= link_to 'Reject', hangout_path(@hangout, hangout: {status: "rejected"}), method: :patch, class: "hangout-button" %>
    <% end %>
    <%= link_to 'Back', dashboard_path, class: "hangout-button" %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>LoanMe</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  <%= stylesheet_pack_tag 'application' %>
</head>

<body>
  <!-- NAVBAR -->
  <%= render 'shared/nav-bar' %>
  <div id="page-container">
      <%= yield %>
  </div>
  <!-- FOOTER -->
  <%= render 'shared/footer' %>
</body>
</html>

app/views/pages/components.html.erb
<!-- <h1>Pages#home</h1>
  <p>Find me in app/views/pages/home.html.erb</p> -->
  <!-- # NAVBAR -->

  <!-- BANNER -->
  <div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/background.png);">
    <div class="container">
      <h1><strong>Loan Me</strong></h1>
      <p>For the lonely.</p>
      <a class="btn btn-success" href="#">Sign Up Now!</a>
    </div>
  </div>

  <!-- Small Banner -->
  <div class="small-banner" style="background-color: #74BEB8;">
    <div class="container">
      <h1><strong>Add text here</strong></h1>
    </div>
  </div>

  <!-- FLASHES -->
  <h2>FLASHES</h2>
  <p>As seen in the bottom right corner. Cycle through them :)</p>
  <div class="flash flash-success alert alert-dismissible fade show" role="alert">
    <span><strong>Yay!</strong> 🎉 you successfully signed in to our service.</span>
    <a data-dismiss="alert" aria-label="Close">
      <i class="fas fa-times"></i>
    </a>
  </div>

  <div class="flash flash-warning alert alert-dismissible fade show" role="alert">
    <span><strong>Mmh</strong> 🤔 seems like you don't have <a href="#">profile picture</a> yet.</span>
    <a data-dismiss="alert" aria-label="Close">
      <i class="fas fa-times"></i>
    </a>
  </div>

  <div class="flash flash-danger alert alert-dismissible fade show" role="alert">
    <span><strong>Oops!</strong> 😱 a problem has occurred while processing your booking.</span>
    <a data-dismiss="alert" aria-label="Close">
      <i class="fas fa-times"></i>
    </a>
  </div>

  <!-- Avatars -->
  <h2>AVATARS</h2>
  <img class="avatar" alt="avatar" src="https://qph.fs.quoracdn.net/main-qimg-342cdbdeae5280924912b8551e49a7c6" />
  <img class="avatar-large" alt="avatar-large" src="https://kitt.lewagon.com/placeholder/users/arthur-littm" />
  <img class="avatar-bordered" alt="avatar-bordered" src="https://kitt.lewagon.com/placeholder/users/sarahlafer" />
  <img class="avatar-square" alt="avatar-square" src="https://kitt.lewagon.com/placeholder/users/krokrob" />

  <!-- SEARCH BAR -->

  <div class="container">
    <div class="row justify-content-center">
      <div class="col-sm-12 col-md-6">
        <h2>SEARCH BAR</h2>
        <form novalidate="novalidate" class="simple_form search" action="/" accept-charset="UTF-8" method="get"><input name="utf8" type="hidden" value="&#x2713;" />
          <div class="search-form-control form-group">
            <input class="form-control string required" type="text" name="search[query]" id="search_query" />
            <button name="button" type="submit" class="btn btn-success">
              <i class="fas fa-search"></i> Search
            </button>
          </div>
        </form>
        <hr>

        <!-- FRIEND CARDS -->
        <h2>FRIEND CARDS</h2>
        <% @profiles.each do |profile| %>
        <%= link_to "#", class: "card-link" do %>
        <div class="card-friend">
          <% if profile.photo.attached? %>
          <%= cl_image_tag profile.photo.key %>
          <% else %>
          <%= cl_image_tag "avatar_ivxvwp" %>
          <% end %>
          <div class="card-friend-infos">
            <h2><%= profile.name %>
              <% if profile.gender == "female" %>
              <i class="fas fa-venus"></i>
              <% elsif profile.gender == "male" %>
              <i class="fas fa-mars"></i>
              <% else %>
              <i class="fas fa-transgender-alt"></i>
              <% end %>
              <%= profile.age %></h2>
              <p>Interests: <%= profile.interest %></p>
            </div>
          </div>
          <% end %>
          <% end %>

          <!-- Hangout Cards -->
          <h2>HANGOUT CARDS</h2>
          <% @hangouts.each do |hangout| %>
          <%= link_to "#", class: "card-link" do %>
          <div class="card-friend">
            <% if hangout.profile.photo.attached? %>
            <%= cl_image_tag hangout.profile.photo.key %>
            <% else %>
            <%= cl_image_tag "avatar_ivxvwp" %>
            <% end %>
            <div class="card-friend-infos">
              <h2><%= hangout.profile.name %>
                <% if hangout.profile.gender == "female" %>
                <i class="fas fa-venus"></i>
                <% elsif hangout.profile.gender == "male" %>
                <i class="fas fa-mars"></i>
                <% else %>
                <i class="fas fa-transgender-alt"></i>
                <% end %>
                <%= hangout.profile.age %></h2>
                <p><%= hangout.date %> - <%= hangout.time %></p>
                <p>Status: <%= hangout.status %></p>
              </div>
            </div>
            <% end %>
            <% end %>


          </div>
        </div>
      </div>


      <!-- FOOTER -->
      <div class="footer">
        <div class="footer-links">
          <a href="#"><i class="fab fa-github"></i></a>
          <a href="#"><i class="fab fa-instagram"></i></a>
          <a href="#"><i class="fab fa-facebook"></i></a>
          <a href="#"><i class="fab fa-twitter"></i></a>
          <a href="#"><i class="fab fa-linkedin"></i></a>
        </div>
        <div class="footer-copyright">
          Don't be lonely, choose Loan Me!
        </div>
      </div>

app/views/pages/home.html.erb
<div class="home">
  <div class="container">
    <div class="row">
      <div class="col-6">
        <h1>Loan Me</h1>
        <br>
        <p>Need a plus one to your sister’s wedding? A one-day boyfriend to impress your parents, or a buddy to go to the movies with?
          <br>
          <br>
          <em>Loan Me</em> is a meeting place for new friends, new opportunities, and new experiences.
          <br>
          <br>
          Sign-up with us to begin your adventure! 
        </p>
      </div>
      <div class="col-6 align-items-end">
        <%= image_tag "talk.svg", class:"image" %>
      </div>
    </div>
  </div>
</div>

app/views/profiles/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-6">
      <div class="ml-2 pl-5">
        <div class="mt-5">
          <div>
            <% if @profile.photo.attached? %>
              <%= cl_image_tag @profile.photo.key, class: "avatar-super" %>
            <% else %>
              <%= cl_image_tag "avatar_ivxvwp", class: "avatar-super" %>
            <% end %>
          </div>

       

          <div class="py-3 text-justify">
            <p><%= @profile.name %>
                <% if @profile.gender == "female" %>
                  <i class="fas fa-venus"></i>
                <% elsif @profile.gender == "male" %>
                  <i class="fas fa-mars"></i>
                <% else %>
                  <i class="fas fa-transgender-alt"></i>
                <% end %>
                <%= @profile.age %></p>
            <p>Interests: <%= @profile.interest.gsub(/[",\[\]]/, "") %></p>
            <p><i class="fas fa-star"></i><%= @profile.average_rating %></p>
          </div>

        <% if policy(@profile).edit?%>
          <%= link_to "Edit Profile", edit_profile_path(@profile), class: "btn btn-success" %>
        <% end %>
        <% if policy(@profile).destroy?%>
          <%= link_to "Delete Profile", profile_path(@profile), method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-danger" %>
        <% end %>
        </div>
      </div>
    </div>

    <% if policy(@hangout).create?%>

      <div class="col-sm-12 col-md-6 mt-5 pt-5">
        <div class="text-center">
          <h3>Book a Hangout with <%= @profile.name %> !</h3>
        </div>
        <div class="form p-3 mt-5 border rounded">
          <%= simple_form_for [@profile, @hangout] do |f| %>
            <%= f.input :date, html5: true, input_html: {min: Date.today} %>
            <%= f.input :time %>
            <%= f.submit "Send",  class: "btn btn-success form-button" %>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
</div>

<div class="nav-bar">
  <div class="row justify-content-between align-items-center">
    <div class="col-12">
      <div class="content d-flex justify-content-end align-items-end">
        <div>
          <% if current_user.profile == @profile %>
            <div class="login">
              <%= link_to dashboard_path do %>
                <div class="d-flex align-items-center">
                <div class="text">
                  <p class="d-inline mr-2">Dashboard</p>
                </div>
                  <i class="fas fa-caret-left d-inline"></i>
                </div>
              <% end %>
            </div>
          <% else %>
            <div class="login">
              <%= link_to profiles_path do %>
                <div class="d-flex align-items-center">
                  <i class="fas fa-caret-left d-inline mr-2"></i>
                  <div class="text">
                    <p class="d-inline">Back</p>
                  </div>
                </div>
              <% end %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="https://github.com/jessicakalip/Loan-Me" target="_blank" ><i class="fab fa-github"></i></a>
    <div class="attribution">Icons made by<a href="https://www.freepik.com" title="Freepik">Freepik</a>from<a href="https://www.flaticon.com/" title="Flaticon">www.flaticon.com</a></div>
  </div>
</div>

app/views/shared/_nav-bar.html.erb
<div class="nav-bar">
  <div class="row justify-content-between align-items-center">
    <div class="col-1">
      <% if user_signed_in? %>
        <div class="dropdown">
          <button class="btn btn-secondary dropdown" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <i class="fas fa-bars drop-down view-activity"></i>
          </button>
          <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
            <ul>
              <li>
                <%= link_to profiles_path do %>
                <p>Find Friends</p>
                <% end %>
              </li>

              <li>
                <%= link_to dashboard_path(tab: "hangout") do %>
                <p>Hangouts</p>
                <% end %>
              </li>

              <li>
                <%= link_to dashboard_path(tab: "request") do %>
                <p>Request</p>
                <% end %>
              </li>

              <li>
                <% if !policy(Profile).create? %>
                  <%= link_to profile_path(current_user.profile) do %>
                  <p>My Profile</p>
                  <% end %>
                <% else %>
                  <%= link_to new_profile_path do %>
                  <p>Create my profile</p>
                  <% end %>
                <% end %>
              </li>
              
              <li>
                <%= link_to edit_user_registration_path do %>
                <p>Change Password</p>
                <% end %>
              </li>
            </ul>
          </div>
        </div>
        
      
      <% end %>
    </div>
    <div class="col-9">
    <% if user_signed_in? %>
      <div class="content d-flex justify-content-end align-items-end">
          <div class="login">
            <%= link_to destroy_user_session_path, method: :delete do %>
            <div class="d-flex align-items-center">
              <div class="text">
                <p class="d-inline mr-2">Log out</p>
              </div>
              <i class="fas fa-caret-right d-inline"></i>
            </div>
            <% end %>
          </div>
        </div>
      <% else %>
        <div class="content d-flex justify-content-end align-items-end">
          <div class="login">
            <%= link_to new_user_registration_path do %>
              <div class="d-flex align-items-center">
              <div class="text">
                <p class="d-inline mr-2">Sign up</p>
              </div>
                <i class="fas fa-caret-right d-inline"></i>
              </div>
            <% end %>
          </div>
          <div class="login">
            <%= link_to new_user_session_path do %>
            <div class="d-flex align-items-center">
              <div class="text">
                <p class="d-inline mr-2">Log in</p>
              </div>
              <i class="fas fa-caret-right d-inline"></i>
            </div>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>